version: '3'
services:
  db:
    container_name: cli_postgres
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password

  redis:
    container_name: redis
    image: redis:5-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  app:
    container_name: todo_container
    image: web_app:1.1
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e production"
    volumes:
      - .:/myapp
    ports:
      - "4000:3000"
    links:
      - "db:cli_postgres"
      - "redis"
      - "web:nginx_web"
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env.prod

  web:
    container_name: nginx_web
    image: nginx
    volumes:
      - /root/Documents/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

volumes:
  redis:
  pg_data:

