default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("DB_IP") { '127.0.0.1' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  encoding: utf8
  database: todolist_dev
  
test:
  <<: *default
  encoding: utf8
  database: todolist_test

production:
  <<: *default
  encoding: utf8
  database: todolist_prod